[project]
name = "bill-splitter"
version = "0.1.0"
description = "A small utility to split bills amongst friends"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Kshitish Deshpande", email = "me@ksdfg.dev" }
]

dependencies = [
    "fastapi[all]>=0.124.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
    "ruff>=0.14.8",
    "ty>=0.0.1a32",
]

[tool.ruff]
line-length = 120
exclude = ["__init__.py"]
